### Handling errors
lets add a `try catch` block like this
```
 try {
          await axios.post('/api/issues', data);
          router.push('/issues');
          
        } catch (error) {
          console.log(error)
        }
      })}
```
Console log is just to see it on the console. This is useful if we had rely on the backend to validate de data.
```
const createIssueSchema = z.object({
  title: z.string().min(1, 'Title is required.').max(255),
  description: z.string().min(1, 'Description is required'),
});
```
Here we added a second argument, `Title..` and `Descrip...`. This is not required because it's not on the client. Lets use the `state hook`,
to show our error `const [error, setError] = useState('')` and then after `catch`, ...`setError('An unexpected error occurred.')`. Head back to
`Radix UI` and look on the left tab for `Callout` and use the code given. Next above the form wrap the entire form within a `<div>` and then add 
this code if there is an error ```
{error && (
        <Callout.Root color="red">
          <Callout.Text>{error}</Callout.Text>
        </Callout.Root>
      )}```
If we try to send an empty field for and `issue` we are going to get an error message `An unexpected error occurred`.
